language: cpp

# use ubuntu 14.04 instead of the default 12.04
dist: trusty

compiler:
    - g++

before_install:
    # save project dir in environment variable
    - PROJECT_DIR=$(pwd)

    # add toolchain repository (for g++ update)
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - sudo apt-get update -qq

install:
    # install lua
    - sudo apt-get install liblua5.2-dev

    # install libcppunit
    - sudo apt-get install libcppunit-1.* libcppunit-dev

    # install newer compiler and set symlink to g++ version 4.9
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
    - sudo ln -sf /usr/bin/g++-4.9 /usr/bin/g++

    # check g++ version
    - $CXX --version
    - g++ --version

    # install can-utils
    - cd
    - git clone https://github.com/linux-can/can-utils
    - cd can-utils
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install

    # setup vcan
    - sudo modprobe vcan
    - sudo ip link add dev vcan0 type vcan
    - sudo ip link set up vcan0

    # test vcan
    - ip link
    - candump vcan0 &
    - cansend vcan0 123#1122334455667788
    - killall candump

    # install isotp
    - cd
    - git clone https://github.com/hartkopp/can-isotp
    - cd can-isotp
    - git apply ../resources/0001-Kernel-version-patch-for-ISO-TP.patch
    - sudo apt-get install build-essential linux-headers-$(uname -r)
    - make
    - sudo make modules_install
    - sudo insmod ./net/can/can-isotp.ko

    # test isotp
    - isotprecv -s 123 -d 321 -l vcan0 &
    - echo 11 22 33 44 55 66 DE AD BE EF | isotpsend -s 321 -d 123 vcan0
    - killall isotprecv

before_script:
    - cd $PROJECT_DIR

script:
    - make
    - make test
